service: notes

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    APP_NAME: My Notes App
    APP_STAGE: ${opt:stage,self:provider.stage}
    SERVICE_NAME: Notes Service



functions:
  createNotes:
    handler: handler.createNotes
    events:
      - http:
          path: notes
          method: post
	
  getNoteById:
    handler: handler.getNotesById
    events:
      - http:
          path: notes/{id}
          method: get

	
resources:
  Resources:
    AccessLogs:
      Type: AWS::Logs::LogGroup
      DeletionPolicy: Retain
      Properties:
        LogGroupName: "/aws/lambda/notes-dev-createNotes"
    AccessLogs1:
      Type: AWS::Logs::LogGroup
      DeletionPolicy: Retain
      Properties:
#       LogGroupName: "/aws/lambda/notes-dev-createNotes"
        LogGroupName: "/aws/lambda/notes-dev-getNoteById"
  extensions:
        DevDashCreateNotesLogGroup:
  #         DependsOn: LambdaLogGroup


        