name: Test
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@main

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.0'

    - name: npm install, build, and test
      run: |
        npm install
 #       npm audit fix
    
    - name: SonarQube Scan
      uses: docker://sonarsource/sonar-scanner-cli:latest
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
